<?xml version='1.0'?>
<robot name = "castor_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- define constants -->

<xacro:property name = " pi_const" value ="3.14159"/>

<!-- BODY LINK DIMENSIONS  -->
<!-- units used in meters -->

 <xacro:property name = "body_length" 
    value ="1"/>
 <xacro:property name = "body_height" 
    value ="0.6"/>
 <xacro:property name = "body_width" 
    value ="0.3"/>

<!-- WHEEL DIMENSIONS  AND CASTOR DIMENSIONS -->
<!-- RADIUS -->
<xacro:property name = "radius" 
    value = "0.15"/>
<! -- WIDTH  WHEEL -- >
<xacro:property name ="width" 
    value ="0.1"/>

<!-- other dimensions -->
 <xacro:property name = "s1" 
    value = "${body_height/2 + radius}"/>
 <xacro:property name = "s2"
 value ="${radius*2}"/>
 <xacro:property name = name "s3"
    value = "${radius*2}"/>
 <xacro:property name = "s4"
   value ="${body_width/2 + width/2}"/>



<!-- MASS NAD INERTIA -->


<!-- DENSITY -->
<!-- BODY LINK -->
<xacro:macro name = "body_link" 
   value = "2710.0"/>
<!-- WHEEL LINK -->
<xacro:property name = "wheel_link" 
   value = "2710.0"/>
<!-- CASTOR LINK -->
<xacro:property name = "castor_link"
   value = "2710.0"/>

<!-- MASS -->
<!-- BODY LINK MASS -->
<xacro:property name = "body_mass"
   value = "${body_linkk*body_length*body_width*body_height}"/>
<!-- WHEEL LINK MASS -->
<xacro:property name = "wheel_mass"
   value = "${wheel_link*pi_const^2*radius*width}"/>
<!-- CASTOR LINK MASS -->
<xacro:property name = "castor_mass"
   value = "${castor_link*(4/3)*pi_const*radius^3}"/>


<!--MOMENT OF INERTIA -->

<!-- BODY LINK MOMENT OF INERTIA -->
<xacro:property name = "Ix_body"
   value = "${(1/12)*body_mass*(body_height^2 + body_width^2)}" />
<xacro:property name = "Iy_body"
   value = "${(1/12)*body_mass*(body_length^2 + body_width^2)}" />
<xacro:property name = "Iz_body"
   value = "${(1/12)*body_mass*(body_length^2 + body_height^2)}" />

<!-- WHEEL LINK MOMENT OF INERTIA -->
<xacro:property name = "Ix_wheel"
   value = "${(1/12*wheel_mass)*(3*radius^2 + width^2)}" />
<xacro:property name = "Iy_wheel"
   value = "${(1/12)*wheel_mass*(radius^2 + width^2)}" />
<xacro:property name = "Iz_wheel"
   value = "${(1/2)*wheel_mass*radius^2}" />

<!-- CASTOR LINK MOMENT OF INERTIA -->
<xacro:property name = "Ix_castor"
   value = "${(2/5)*castor_mass*radius^3}" />
<xacro:property name = "Iy_castor"
   value = "${(2/5)*castor_mass*radius^3}" />
<xacro:property name = "Iz_castor"
   value = "${(2/5)*castor_mass*radius^3}" />




</robot>