<?xml version='1.0'?>
<robot name = "castor_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- define constants -->

<xacro:property name = " pi_const" value ="3.14159"/>

<!-- BODY LINK DIMENSIONS  -->
<!-- units used in meters -->

 <xacro:property name = "body_length" 
    value ="1"/>
 <xacro:property name = "body_width" 
    value ="0.6"/>
 <xacro:property name = "body_height" 
    value ="0.3"/>

<!-- WHEEL DIMENSIONS  AND CASTOR DIMENSIONS -->
<!-- RADIUS -->
  <xacro:property name = "radius" 
    value = "0.15"/>
<! -- WIDTH  WHEEL -- >
    <xacro:property name ="width" 
    value ="0.1"/>

<!-- other dimensions -->
 <xacro:property name = "s1" 
    value = "${body_height/2 + radius}"/>
 <xacro:property name = "s2"
 value ="${radius*2}"/>
 <xacro:property name = name "s3"
    value = "${radius*2}"/>
 <xacro:property name = "s4"
 value ="${body_width/2 + width/2}"/>

<!-- MASS NAD INERTIA -->

</robot>