<?xml version="1.0"?>
<robot name="castor_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- ========================================================= -->
<!-- ===================== CONSTANTS ========================= -->
<!-- ========================================================= -->

<xacro:property name="pi" value="3.141592653589793"/>

<!-- ================= BODY DIMENSIONS (meters) =============== -->

<xacro:property name="body_length" value="1.0"/>
<xacro:property name="body_width"  value="0.6"/>
<xacro:property name="body_height" value="0.3"/>

<!-- ================= WHEEL DIMENSIONS ======================= -->

<xacro:property name="radius" value="0.15"/>
<xacro:property name="width"  value="0.1"/>

<!-- ========================================================= -->
<!-- ========== GEOMETRIC OFFSETS (MATCH DIAGRAM) ============= -->
<!-- ========================================================= -->

<!-- vertical -->
<xacro:property name="z_wheel" value="${radius}"/>
<xacro:property name="z_body"  value="${radius + body_height/2}"/>

<!-- longitudinal -->
<!-- caster is at FRONT (+X), wheels are behind -->
<xacro:property name="x_caster" value="${ body_length/2 - radius}"/>
<xacro:property name="x_wheel"  value="${-body_length/2 + radius}"/>

<!-- lateral -->
<xacro:property name="y_wheel" value="${body_width/2 + width/2}"/>

<!-- ========================================================= -->
<!-- ======================= MASS ============================ -->
<!-- ========================================================= -->

<xacro:property name="body_mass"   value="25.0"/>
<xacro:property name="wheel_mass"  value="1.5"/>
<xacro:property name="caster_mass" value="0.5"/>

<!-- ========================================================= -->
<!-- ===================== INERTIA ============================ -->
<!-- ========================================================= -->

<!-- BODY -->
<xacro:property name="Ix_body"
  value="${(1/12)*body_mass*(body_height*body_height + body_width*body_width)}"/>
<xacro:property name="Iy_body"
  value="${(1/12)*body_mass*(body_length*body_length + body_width*body_width)}"/>
<xacro:property name="Iz_body"
  value="${(1/12)*body_mass*(body_length*body_length + body_height*body_height)}"/>

<!-- WHEEL -->
<xacro:property name="Ix_wheel"
  value="${(1/12)*wheel_mass*(3*radius*radius + width*width)}"/>
<xacro:property name="Iy_wheel"
  value="${(1/12)*wheel_mass*(3*radius*radius + width*width)}"/>
<xacro:property name="Iz_wheel"
  value="${0.5*wheel_mass*radius*radius}"/>

<!-- CASTER -->
<xacro:property name="I_caster"
  value="${(2/5)*caster_mass*radius*radius}"/>

<!-- ========================================================= -->
<!-- ==================== INERTIAL MACROS ==================== -->
<!-- ========================================================= -->

<xacro:macro name="body_inertial">
  <inertial>
    <origin xyz="0 0 ${z_body}"/>
    <mass value="${body_mass}"/>
    <inertia
      ixx="${Ix_body}" ixy="0" ixz="0"
      iyy="${Iy_body}" iyz="0"
      izz="${Iz_body}"/>
  </inertial>
</xacro:macro>

<xacro:macro name="wheel_inertial">
  <inertial>
    <mass value="${wheel_mass}"/>
    <inertia
      ixx="${Ix_wheel}" ixy="0" ixz="0"
      iyy="${Iy_wheel}" iyz="0"
      izz="${Iz_wheel}"/>
  </inertial>
</xacro:macro>

<xacro:macro name="caster_inertial">
  <inertial>
    <mass value="${caster_mass}"/>
    <inertia
      ixx="${I_caster}" ixy="0" ixz="0"
      iyy="${I_caster}" iyz="0"
      izz="${I_caster}"/>
  </inertial>
</xacro:macro>

<!-- ========================================================= -->
<!-- ====================== BASE ============================== -->
<!-- ========================================================= -->

<link name="base_footprint"/>

<joint name="base_to_body" type="fixed">
  <parent link="base_footprint"/>
  <child link="body_link"/>
  <origin xyz="0 0 0"/>
</joint>

<!-- ========================================================= -->
<!-- ====================== BODY ============================== -->
<!-- ========================================================= -->

<link name="body_link">
  <visual>
    <geometry>
      <box size="${body_length} ${body_width} ${body_height}"/>
    </geometry>
    <origin xyz="0 0 ${z_body}"/>
  </visual>

  <collision>
    <geometry>
      <box size="${body_length} ${body_width} ${body_height}"/>
    </geometry>
    <origin xyz="0 0 ${z_body}"/>
  </collision>

  <xacro:body_inertial/>
</link>

<!-- ========================================================= -->
<!-- ====================== LEFT WHEEL ======================= -->
<!-- ========================================================= -->

<joint name="wheel_left_joint" type="continuous">
  <parent link="body_link"/>
  <child link="wheel_left_link"/>
  <origin xyz="${x_wheel} ${ y_wheel} ${z_wheel}"/>
  <axis xyz="0 1 0"/>
</joint>

<link name="wheel_left_link">
  <visual>
    <geometry>
      <cylinder radius="${radius}" length="${width}"/>
    </geometry>
    <origin rpy="1.5708 0 0"/>
  </visual>

  <collision>
    <geometry>
      <cylinder radius="${radius}" length="${width}"/>
    </geometry>
    <origin rpy="1.5708 0 0"/>
  </collision>

  <xacro:wheel_inertial/>
</link>

<!-- ========================================================= -->
<!-- ====================== RIGHT WHEEL ====================== -->
<!-- ========================================================= -->

<joint name="wheel_right_joint" type="continuous">
  <parent link="body_link"/>
  <child link="wheel_right_link"/>
  <origin xyz="${x_wheel} ${-y_wheel} ${z_wheel}"/>
  <axis xyz="0 1 0"/>
</joint>

<link name="wheel_right_link">
  <visual>
    <geometry>
      <cylinder radius="${radius}" length="${width}"/>
    </geometry>
    <origin rpy="1.5708 0 0"/>
  </visual>

  <collision>
    <geometry>
      <cylinder radius="${radius}" length="${width}"/>
    </geometry>
    <origin rpy="1.5708 0 0"/>
  </collision>

  <xacro:wheel_inertial/>
</link>

<!-- ========================================================= -->
<!-- ====================== FRONT CASTER ==================== -->
<!-- ========================================================= -->

<joint name="caster_joint" type="fixed">
  <parent link="body_link"/>
  <child link="caster_link"/>
  <origin xyz="${x_caster} 0 ${z_wheel}"/>
</joint>

<link name="caster_link">
  <visual>
    <geometry>
      <geometry>
        <sphere radius="${radius}"/>
      </geometry> 
    </geometry>
    <origin rpy="1.5708 0 0"/>
  </visual>

  <collision>
    <geometry>
        <sphere radius="${radius}"/>
    </geometry>
    <origin rpy="1.5708 0 0"/>
  </collision>

  <xacro:caster_inertial/>
</link>

</robot>
