<?xml version='1.0'?>
<robot name = "castor_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- define constants -->

<xacro:property name = "ohm" value ="3.14159"/>

<!-- BODY LINK DIMENSIONS  -->
<!-- units used in meters -->

<xacro:property name = "body_length" value ="1.0"/>
<xacro:property name = "body_width"  value ="0.6"/>
<xacro:property name = "body_height" value ="0.3"/>

<!-- WHEEL DIMENSIONS  AND CASTOR DIMENSIONS -->
<xacro:property name = "radius" value = "0.15"/>
<xacro:property name ="width"  value ="0.1"/>

<!-- other dimensions -->
<xacro:property name = "s1" value = "${body_height/2}"/>

<!-- ✅ FIXED -->
<xacro:property name = "s2" value ="${body_length/2 - radius}"/>

<xacro:property name = "s3" value = "${radius*2}"/>

<!-- ✅ FIXED -->
<xacro:property name = "s4" value ="${body_width/2}"/>

<!-- MASS NAD INERTIA -->

<xacro:property name = "body"   value = "2710.0"/>
<xacro:property name = "wheel"  value = "2710.0"/>
<xacro:property name = "castor" value = "2710.0"/>

<!-- MASS -->
<xacro:property name = "body_mass"
   value = "${body*body_length*body_width*body_height}"/>

<xacro:property name = "wheel_mass"
   value = "${wheel*ohm*radius*radius*width}"/>

<xacro:property name = "castor_mass"
   value = "${castor*(4.0/3.0)*ohm*radius*radius*radius}"/>

<!-- MOMENT OF INERTIA -->

<xacro:property name = "Ix_body"
   value = "${(1/12)*body_mass*(body_height*body_height + body_width*body_width)}"/>
<xacro:property name = "Iy_body"
   value = "${(1/12)*body_mass*(body_length*body_length + body_width*body_width)}"/>
<xacro:property name = "Iz_body"
   value = "${(1/12)*body_mass*(body_length*body_length + body_height*body_height)}"/>

<xacro:property name="Ix_wheel"
   value="${(1.0/12.0)*wheel_mass*(3*radius*radius + width*width)}"/>
<xacro:property name="Iy_wheel"
   value="${(1.0/12.0)*wheel_mass*(3*radius*radius + width*width)}"/>
<xacro:property name="Iz_wheel"
   value="${(0.5)*wheel_mass*radius*radius}"/>

<xacro:property name = "Ix_castor"
   value = "${(2.0/5.0)*castor_mass*radius*radius}"/>
<xacro:property name = "Iy_castor"
   value = "${(2.0/5.0)*castor_mass*radius*radius}"/>
<xacro:property name = "Iz_castor"
   value = "${(2.0/5.0)*castor_mass*radius*radius}"/>

<xacro:include filename ="$(find mobile_robot)/model/robot.gazebo"/>

<!-- BASE -->
<link name="base_footprint"/>

<joint name="body_link_joint" type="fixed">
  <parent link="base_footprint"/>
  <child link="body_link"/>
  <origin xyz="0 0 0"/>
</joint>

<!-- BODY -->
<link name="body_link">
  <visual>
    <geometry>
      <box size="${body_length} ${body_width} ${body_height}"/>
    </geometry>
    <origin xyz="0 0 ${s1}"/>
  </visual>

  <collision>
    <geometry>
      <box size="${body_length} ${body_width} ${body_height}"/>
    </geometry>
    <origin xyz="0 0 ${s1}"/>
  </collision>

  <xacro:body_link_macro/>
</link>

<!-- LEFT WHEEL -->
<joint name="wheel1_joint" type="continuous">
  <parent link="body_link"/>
  <child link="wheel1_link"/>
  <origin xyz="${-s2} ${-s4} ${radius}"/>
  <axis xyz="0 1 0"/>
</joint>

<link name="wheel1_link">
  <visual>
    <geometry>
      <cylinder length="${width}" radius="${radius}"/>
    </geometry>
    <origin rpy="1.570795 0 0"/>
  </visual>

  <collision>
    <geometry>
      <cylinder length="${width}" radius="${radius}"/>
    </geometry>
    <origin rpy="1.570795 0 0"/>
  </collision>

  <xacro:wheel_link_macro/>
</link>

<!-- RIGHT WHEEL -->
<joint name="wheel2_joint" type="continuous">
  <parent link="body_link"/>
  <child link="wheel2_link"/>
  <origin xyz="${-s2} ${s4} ${radius}"/>
  <axis xyz="0 1 0"/>
</joint>

<link name="wheel2_link">
  <visual>
    <geometry>
      <cylinder length="${width}" radius="${radius}"/>
    </geometry>
    <origin rpy="1.570795 0 0"/>
  </visual>

  <collision>
    <geometry>
      <cylinder length="${width}" radius="${radius}"/>
    </geometry>
    <origin rpy="1.570795 0 0"/>
  </collision>

  <xacro:wheel_link_macro/>
</link>

<!-- CASTER -->
<joint name="caster_joint" type="fixed">
  <parent link="body_link"/>
  <child link="caster_link"/>
  <origin xyz="${body_length/2 - radius} 0 ${radius}"/>
</joint>

<link name="caster_link">
  <visual>
    <geometry>
      <sphere radius="${radius}"/>
    </geometry>
  </visual>

  <collision>
    <geometry>
      <sphere radius="${radius}"/>
    </geometry>
  </collision>

  <xacro:castor_link_macro/>
</link>

</robot>
