<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro">

<gazebo reference = "body_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/Red</material>
</gazebo>

<gazebo reference = "wheel1_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <material>Gazebo/Yellow</material>
</gazebo>

<gazebo reference = "wheel2_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <material>Gazebo/Yellow</material>
</gazebo>

<gazebo reference = "caster_link">
    <mu1>0.00002</mu1>
    <mu2>0.00002</mu2>
    <material>Gazebo/Blue</material>
</gazebo>

<gazebo>
    <plugin filename = "libgz-sim-diff-drive-system.so" name="gz::sim::systems::DiffDrive">

        <left_joint>wheel1_joint</left_joint>
        <right_joint>wheel2_joint</right_joint>

        <wheel_separation>${2*s4}</wheel_separation>
        <wheel_diameter>${2*radius}</wheel_diameter>

        <max_wheel_torque>100</max_wheel_torque>
        <max_wheel_acceleration>10.0</max_wheel_acceleration>

        <topic>/cmd_vel</topic>
        <tf_topic>/tf</tf_topic>
        <odom_topic>/odom</odom_topic>
        <frame_id>odom</frame_id>
        <child_frame_id>base_footprint</child_frame_id>
        <odom_publisher_frequency>30</odom_publisher_frequency>
    </plugin>

    <plugin filename="libgz-sim-joint-state-publisher-system.so" name="gz::sim::systems::JointStatePublisher">
        <topic>/joint_states</topic>
        <joint_name>wheel1_joint</joint_name>
        <joint_name>wheel2_joint</joint_name>
    </plugin>   
</gazebo>

</robot>
